### ISSUE TITLE
Not all displays listed

### ISSUE THREAD

**Issue by chscf** [jceb/srandrd#10]
Hello,

I'm using srandrd-0.6.1 on an xorg-server-1.21.1.6 on a laptop with one internal and one external display. When I call xrandr, I get this:

<pre>
bash-5.0# xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
eDP1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.01*+  59.93  
   1680x1050     59.88  
   1400x1050     59.98  
   1600x900      60.00    59.95    59.82  
   1280x1024     60.02  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1368x768      60.00    59.88    59.85  
   1280x800      59.81    59.91  
   1280x720      59.86    60.00    59.74  
   1024x768      60.00  
   1024x576      60.00    59.90    59.82  
   960x540       60.00    59.63    59.82  
   800x600       60.32    56.25  
   864x486       60.00    59.92    59.57  
   640x480       59.94  
   720x405       59.51    60.00    58.99  
   640x360       59.84    59.32    60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 470mm x 260mm
   1920x1080     60.00*+  60.00    50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   832x624       74.55  
   800x600       75.00    60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
DVI-I-1-1 disconnected (normal left inverted right x axis y axis)
</pre>

When I call "srandrd list", I only get the internal display:

<pre>
bash-5.0# srandrd list
eDP1 CF268C7800000004
</pre>

When I disconnect the external Display, then start srandrd as daemon, and then connect the external display again, I get the correct event and my display handling script is called:

<pre>
bash-5.0# srandrd -v -n /usr/SUPERSHEEP/bin/dsp_hndl.sh 
Event: HDMI1 connected
Time: 3633511
CRTC: 63
Size: 1920x1080
EDID (vendor, product, serial): D109790C00005445
</pre>

When I now I call "srandrd list", I still get only the internal display listed.

Is there anything obvious I'm doing wrong here?

Thanks and best regards,
Christian

**Comment by jceb** [comment]
Thanks for the reporting the issue. I don't have any issues on my computer. Would you be willing to dig a little deeper on yours to identify the issue?

**Comment by chscf** [comment]
Sure, if you tell me where to dig ;)

I already did a little debugging, and I found out that in iter_crts after these calls:

<pre>
	si = XineramaQueryScreens(dpy, &nscreens);
	mi = XRRGetMonitors(dpy, DefaultRootWindow(dpy), True, &nmonitors);
</pre>

both nscreens and nmonitors are 1. But I'm not much of an X11 expert, so maybe this is ok?

And I have to add that this happens on a self-tailored linux system, where everything is compiled and configured by myself; so maybe it's a just configuration issue from my side...

Thanks and regards,
Christian

**Comment by chscf** [comment]
Hi,

any more test I could do?

Thanks,
Christian

**Comment by RainerKuemmerle** [comment]
Just some comment on how to reproduce this on my end:
```
$ xrandr
Screen 0: minimum 320 x 200, current 3840 x 1080, maximum 16384 x 16384
eDP connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.05*+
   1680x1050     60.05  
   1280x1024     60.05  
   1440x900      60.05  
   1280x800      60.05  
   1280x720      60.05  
   1024x768      60.05  
   800x600       60.05  
   640x480       60.05  
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     59.93*+  60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     60.02  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DisplayPort-2 disconnected (normal left inverted right x axis y axis)
DisplayPort-3 disconnected (normal left inverted right x axis y axis)
```
Above is two monitors arranged side by side and it works as expected:
```
$ srandrd list
DisplayPort-1 6D1E56CC0000DA41
eDP AF06403D00000000
```

If I change them to be on top of each with the following xrandr output
```
$ xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP connected 1920x1080+0+0 (normal left inverted right x axis y axis) 309mm x 174mm
   1920x1080     60.05*+
   1680x1050     60.05  
   1280x1024     60.05  
   1440x900      60.05  
   1280x800      60.05  
   1280x720      60.05  
   1024x768      60.05  
   800x600       60.05  
   640x480       60.05  
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-0 disconnected (normal left inverted right x axis y axis)
DisplayPort-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     59.93*+  60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     60.02  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
DisplayPort-2 disconnected (normal left inverted right x axis y axis)
DisplayPort-3 disconnected (normal left inverted right x axis y axis)
```
`srandrd list` only outputs the primary monitor.

```
$ srandrd list
DisplayPort-1 6D1E56CC0000DA41
```

For me the above case works as expected when dropping breaking the loop - but far from being an expert in X.
```
$ git diff
diff --git a/srandrd.c b/srandrd.c
index d263573..b0631aa 100644
--- a/srandrd.c
+++ b/srandrd.c
@@ -226,9 +226,6 @@ iter_crtcs(Display * dpy, void (*f) (Display *, char *, char *, int))
                                        f(dpy, info->name, edid, sid);
                                        XRRFreeOutputInfo(info);
                                }
-                               if (i == sid) {
-                                       break;
-                               }
                        }
                }
                XFree(si);
```
@jceb Does this sound reasonable?

**Comment by jceb** [comment]
Ah, interesting. Thank you for digging into it! I can see that this makes sense. I'll take a look at it.
If you could continue to test the code with the patch, I'd be very happy. Hope there will be no side effects.

**Comment by schoolsplay** [comment]
Hi, I had the same issues but much simpler. (This is on a HP all-in-one device, but 'normal' pc and monitor is the same)
Disconnected HDMI or connected HDMI the output shows always the build-in screen only:
$ ./srandrd list
eDP-1 0E222D4000000000

When applying the patch from  RainerKuemmerle it works as expected:
(Connected HDMI)
$ .srandrd list
eDP-1 0E222D4000000000
HDMI-1 2D4C0C3900000000

(Disconnect HDMI)
$ ./srandrd list
eDP-1 0E222D4000000000

PS, this is just trial and error, I have no clue what the original piece code should do ;-)
We have many different hardware where we gonna use this briljant deamon  so if we find issues with this patch I will report it.

**Comment by jceb** [comment]
Thanks for verifying. I applied the patch.

**Comment by schoolsplay** [comment]
Just FYI: without the patch 'srandrd list' still has issues but with or without the patch 'srandrd display_handler' does receive the correct connected/disconnected device.
And with or without the patch the display_handler receives the event twice. Not sure why that is, only one instance is running.
So the patch seems to only affect the 'list' command.
