### ISSUE TITLE
Initially connected displays are reported incorrectly by srandrd -e 

### ISSUE THREAD

**Issue by vlaci** [jceb/srandrd#2]
See the following example:
```
$ srandrd -e -n sh -c "echo \$SRANDRD_ACTION"
eDP1 AE0D148100000000
connected
DP1-2 AC10407234353253
connected
```
Events occuring after srandrd is started are formatted properly:
```
DP1-1 disconnected
```

**Comment by jceb** [comment]
Which version did you use?  I can reproduce the issue with the latest version: ea8afe46

**Comment by notslang** [comment]
I'm having the same issue with version `0.6.0`.

```
$ srandrd -V
    This is : srandrd
    Version : 0.6.0
  Builddate : Jul 18 2018 21:46:26
  Copyright : (C) 2012-2014 Stefan Bolte, 2016 Jan Christoph Ebersbach
    License : MIT/X Consortium
```

**Comment by jceb** [comment]
I'm not sure how this can happen.  What's the output of `srandrd list`?

**Comment by notslang** [comment]
This is what it gives me:

```
$ srandrd list
eDP1 1006A02A00000000
DP1 AC10A0B8314A4D55
DP2 AC1040BD4144594C
```

**Comment by jceb** [comment]
Looks good.  I'm still confused about how the ID could get into `$SRANDRD_ACTION`.  If you could debug the error on your computer I'd be very happy!

**Comment by jceb** [comment]
I think the issue has been solved in the latest version.
