### ISSUE TITLE
Crash after suspend

### ISSUE THREAD

**Issue by kecsap** [jceb/srandrd#7]
Op.system: Ubuntu 18.04
Laptop: Lenovo X1 Yoga 1st gen
Xorg versions:
ii  xserver-xorg                          1:7.7+19ubuntu7.1                         amd64        X.Org X server
ii  xserver-xorg-core                  2:1.19.6-1ubuntu4.2                       amd64        Xorg X server - core server
ii  xserver-xorg-video-intel         2:2.99.917+git1902220732.9e6e00~oibaf~b     amd64        X.Org X server -- Intel i8xx, i9xx display driver

Symptom:
Run the daemon with a simple shell script:
/usr/bin/srandrd -v -n myscript.sh

```
#!/bin/bash

export DISPLAY=:1
export XAUTHORITY=/home/user/.Xauthority

case "${SRANDRD_OUTPUT} ${SRANDRD_EVENT}" in
  "DVI-I-1-1 connected") sleep 5 && xsetwacom set "Wacom Pen and multitouch sensor Finger touch" MapToOutput eDP1 ;;
  "DVI-I-1-1 disconnected") sleep 5 && xsetwacom set "Wacom Pen and multitouch sensor Finger touch" MapToOutput eDP1 ;;
esac
```

If the laptop is suspended for a longer time, srandrd crashes with:

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  8 (RRGetScreenResources)
  Resource id in failed request:  0x0
  Serial number of failed request:  13
  Current serial number in output stream:  13
```
Gdb produces no backtrace, simple "No stack". There is nothing special in my config. I don't connect or disconnect any monitor while the laptop is suspended. The laptop is not on docking station.

xrandr shows the following config:
eDP1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
DVI-I-1-1 disconnected (normal left inverted right x axis y axis)

I use the Intel GPU with this xorg config:

```
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "sna"
   Option      "TearFree"    "true"
   Option      "DRI"    "3"
EndSection
```

Is it possible that there is some race condition? Maybe xorg emits some connecting/disconnecting signals before suspend?

**Comment by jceb** [comment]
Please try the latest version of srandrd. If the issue still exists, please reopen.
